---
resources:
- name: fixed_time_manual
  type: time
  icon: clock-outline
  source:
    location: Asia/Kolkata
    start: ((start))
    stop: ((stop))
    interval: 5m

jobs:
- name: job
  public: true
  plan:
  - get: fixed_time_manual
    trigger: true
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello, world!"]
