---
resources:
- name: fixed_time_manual
  type: time
  icon: clock-outline
  source:
    start: ((start))
    stop: ((stop))

jobs:
- name: job
  public: true
  plan:
#  - get: fixed_time_manual
    trigger: true
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: curlimages/curl }
      run:
        path: echo
        args: ["Hello, world!"]
